### ISSUE TITLE
A little doubtful

### ISSUE THREAD

**Issue by daixiangzi** [locuslab/llava-token-compression#1]
Excellent work!

**Comment by daixiangzi** [comment]
Why are only a few token nums compared, and not 144 or 72? Is it because your method only has an advantage when there are fewer tokens?

**Comment by SachinG007** [comment]
Yes, that is correct. Based on the main insights from our paper that compute optimal inference requires only a few tokens, we wanted to focus on building approaches tailored for that regime.
Intuitively, at high tokens regime (144 or 72), you don't really need to do query based token compression, as you can pretty much capture the whole image with these many tokens. Our approach will boil down to TokenPacker in this regime. 
We wanted to take initial steps towards building approaches tailored for 1 or 4 or 16 tokens, as that gives compute optimal inference.

Thanks

**Comment by daixiangzi** [comment]
ok,thank you for your reply
