### ISSUE TITLE
Details about pretraining and finetuning configurations

### ISSUE THREAD

**Issue by Jingfeng0705** [locuslab/llava-token-compression#2]
Hi, thanks for the excellent work! I am trying to replicate the training process. What type of GPU you used and how many you used during pretraining and fine-tuning?

**Comment by kevinli573** [comment]
We used a mix of A6000 and A100's. Both pretraining and fine-tuning used 4 GPUs per run.

**Comment by Jingfeng0705** [comment]
Got it, thanks!
