### ISSUE TITLE
A bug in inference phase

### ISSUE THREAD

**Issue by Jingfeng0705** [locuslab/llava-token-compression#4]
Hi! I encountered a bug during the inference phase (I trained the model with LoRA). 
```
text_input_tokens = self.llm_tokenizer(text, padding=True, return_tensors='pt').to(device=self.device)
TypeError: 'NoneType' object is not callable
```
I did some debugging and found out the reason of this issue is that `vision_tower.llm_tokenizer` and `vision_tower.llm_pointer` are both defined by the function `initialize_vision_modules` in the training phase. But in the inference phase, when it loads model with `load_pretrained_model` without calling `initialize_vision_modules`, those two variables used in QueCC are left undefined. I wonder is there any solution to this bug?

Thanks in advance for your time!

**Comment by Jingfeng0705** [comment]
Solved it by adding
```
model.get_model().vision_tower = build_vision_tower(
                    lora_cfg_pretrained, 
                    delay_load=True,
                    llm_pointer=model,
                    llm_tokenizer=tokenizer
)
```
after [here](https://github.com/locuslab/llava-token-compression/blob/bdedebdf8f4bf7a48c916357ec1dc5dc2720b606/llava/model/builder.py#L64). May need to double check for any potential harm to inference.

**Comment by kevinli573** [comment]
Let us take a closer look into this issue. A lot of the code was written during our summer internship and the code transfer had to deal with company internal policies, so we might've missed copying over something.

I think your fix should be fine, as one just needs to pass the tokenizer and model pointer to the encoder.

**Comment by kevinli573** [comment]
Also, you might have to pass in the LLM component of the VLM instead of the VLM itself.

**Comment by Jingfeng0705** [comment]
Thanks for your double-check! It turns out that this [update](https://github.com/locuslab/llava-token-compression/issues/4#issuecomment-2487084501) is enough and I got evaluation results very similar to those in the QueCC paper. Thanks again for the great work!

**Comment by kevinli573** [comment]
Great, thanks for reporting back! We'll update the repo shortly with this fix.

**Comment by mzamini92** [comment]
Hi. I tried to use it for gqa and I still get 
```
  File "/lava-token-compression/llava/model/multimodal_encoder/clip_encoder.py", line 90, in forward
    text_input_tokens = self.llm_tokenizer(text, padding=True, return_tensors='pt').to(device=self.device)
TypeError: 'NoneType' object is not callable
```
